### ISSUE TITLE
友链好像有点小问题

### ISSUE THREAD

**Issue by sinsong** [amaki-aria/amaki-aria.github.io#7]
我记得我之前改过：[32394ff](https://github.com/amaki-aria/amaki-aria.github.io/commit/32394ff0debe044d579a02000aa59f4c6dccba9b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R47)
怎么又改回去了（苦笑）：[8b16010](https://github.com/amaki-aria/amaki-aria.github.io/commit/8b160105a9a552398755b965fd41a36a772f51ac#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R56)
（小声的）应该是：https://blog.literalkernel.work/

**Comment by Gesrua** [comment]
我在之前也发现链接失效，没想到以前还改过一次，小梦梦笨笨的。
